name: Auth and User Module
description: User management and authentication system
title: "[AUTH] "
labels: ["auth"]

body:
  - type: markdown
    attributes:
      value: |
        Select one or more tasks.

  - type: checkboxes
    id: user
    attributes:
      label: User Module
      options:
        - label: Create User schema and model
        - label: Register user endpoint
        - label: Login user endpoint
        - label: Hash password using bcryptjs
        - label: Generate JWT token
        - label: Define roles (admin, user)

  - type: checkboxes
    id: auth
    attributes:
      label: Authentication & Authorization
      options:
        - label: Protect routes using JWT
        - label: Only authenticated users can access protected routes
        - label: Role-based access control (Admin full CRUD / User read only)