name: Auth and User Module
description: Handle authentication and user logic
title: "[AUTH] "
labels: ["auth"]

body:
  - type: checkboxes
    id: tasks
    attributes:
      label: Tasks
      options:
        - label: Create User schema and model
        - label: Register user endpoint
        - label: Login user endpoint
        - label: Hash password using bcryptjs
        - label: Generate JWT token
        - label: Define roles (admin, user)
        - label: Protect routes using JWT
        - label: Role-based access control