name: Middleware and System Configuration
description: Middleware and system setup
title: "[MIDDLEWARE] "
labels: ["middleware"]

body:
  - type: markdown
    attributes:
      value: |
        Select one or more tasks.

  - type: checkboxes
    id: middleware
    attributes:
      label: Middleware
      options:
        - label: Authentication middleware (verify JWT)
        - label: Role middleware (admin/user)
        - label: Error handling middleware
        - label: Logger (morgan)

  - type: checkboxes
    id: system
    attributes:
      label: System Setup
      options:
        - label: Setup Express app
        - label: Setup MongoDB connection using Mongoose
        - label: Setup environment variables

  - type: checkboxes
    id: bonus
    attributes:
      label: Bonus Features
      options:
        - label: Rate limiting
        - label: Logging system